// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

///Name: Gerald Vinyeta, Olivia Ozbaki, Joe Kehoe, Xirui Yu
///Date: 12/14/2022
///Description: Auto-generated flutterfire file describing firebase options
///             for different platforms
///Bugs: N/A
///Reflection: N/A
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL4QlXuZHt3c4qEtAFoxd2u8GDRCL0-pI',
    appId: '1:440052823918:web:3856b6daf9c5f8d584f37f',
    messagingSenderId: '440052823918',
    projectId: 'time-tips',
    authDomain: 'time-tips.firebaseapp.com',
    storageBucket: 'time-tips.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClvv4XrnID7-Koj0P5CSj96Vv2pEsYIG8',
    appId: '1:440052823918:android:e42571bf1efa6bcf84f37f',
    messagingSenderId: '440052823918',
    projectId: 'time-tips',
    storageBucket: 'time-tips.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6z6QCGug_lGLllml3m72u2Kf5kSRrpZ4',
    appId: '1:440052823918:ios:6de88456a643ba0d84f37f',
    messagingSenderId: '440052823918',
    projectId: 'time-tips',
    storageBucket: 'time-tips.appspot.com',
    iosClientId:
        '440052823918-026ueqibbqpolpba583ktupv9vqvuk0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6z6QCGug_lGLllml3m72u2Kf5kSRrpZ4',
    appId: '1:440052823918:ios:6de88456a643ba0d84f37f',
    messagingSenderId: '440052823918',
    projectId: 'time-tips',
    storageBucket: 'time-tips.appspot.com',
    iosClientId:
        '440052823918-026ueqibbqpolpba583ktupv9vqvuk0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
